[project]
name = "tata"
version = "0.1.0"
description = "TATA stands for TATA-Assisted Teaching Assistant. Helper for human TAs to grade and provide feedback on student assignments. It uses LLMs to analyze student work and generate feedback, and it can also detect potential plagiarism."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "copydetect>=0.5.0",
    "instructor>=1.15.1",
    "markitdown[all]>=0.1.5",
    "nbformat>=5.10.4",
    "nbconvert>=7.17.1",
    "openai>=2.34.0",
    "pydantic-settings>=2.14.0",
    "rich>=14.3.4",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
    "jupyter>=1.1.1",
    "pydantic>=2.13.3",
    "canvasapi>=3.6.0",
    "textual>=8.2.8",
    "textual-serve>=1.1.3",
    "sentence-transformers>=6.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
tui = "src.tata_app:run"

[tool.hatch.build.targets.wheel]
packages = ["misc", "src"]

[tool.hatch.build.targets.wheel.force-include]
"src/score_review.tcss" = "src/score_review.tcss"
