"""Preprocess stage: re-export facade for :mod:`src.shared.convert`,
:mod:`src.shared.screenshots` and :mod:`src.shared.pipeline` (the
module was split on 2026-09-08; import paths are unchanged).
"""

from __future__ import annotations

from .convert import (
    _SUFFIX_FORMATS,
    SUPPORTED_INPUT_FORMATS,
    _clean_filename,
    _convert_html_tables_to_markdown,
    _convert_markdown,
    _format_for_suffix,
    _markdown_escape_cell,
    _normalize_dtype_label_html,
    _remove_base64_images,
    _strip_canvas_suffix,
    _strip_colab_dataframe_widgets,
    _table_html_to_markdown,
    _TableHTMLParser,
    convert_docx_to_markdown,
    convert_html_to_markdown,
    convert_ipynb_to_markdown,
    convert_pdf_to_markdown,
    convert_pptx_to_markdown,
)
from .pipeline import (
    ProcessingCliOptions,
    _cached,
    _item_files,
    _item_hash_and_src,
    _iter_raw_items,
    _normalize_input_formats,
    _output_stem,
    _postprocess_markdown,
    _preprocess_pending,
    _process_single_file,
    _resolve_template_base,
    _screenshots_missing,
    _submission_stamp,
    main,
    pending_preprocess_items,
    preprocess_assignment,
    preprocess_item_hashes,
)
from .screenshots import (
    _cleanup_stem_shots,
    _extract_embedded_images,
    _image_to_pdf,
    _pdftoppm_pages,
    _render_screenshots,
    _render_stem_screenshots,
    _shift_page,
)

__all__ = [
    "SUPPORTED_INPUT_FORMATS",
    "_SUFFIX_FORMATS",
    "ProcessingCliOptions",
    "_TableHTMLParser",
    "_cached",
    "_clean_filename",
    "_cleanup_stem_shots",
    "_convert_html_tables_to_markdown",
    "_convert_markdown",
    "_extract_embedded_images",
    "_format_for_suffix",
    "_image_to_pdf",
    "_item_files",
    "_item_hash_and_src",
    "_iter_raw_items",
    "_markdown_escape_cell",
    "_normalize_dtype_label_html",
    "_normalize_input_formats",
    "_output_stem",
    "_pdftoppm_pages",
    "_postprocess_markdown",
    "_preprocess_pending",
    "_process_single_file",
    "_remove_base64_images",
    "_render_screenshots",
    "_render_stem_screenshots",
    "_resolve_template_base",
    "_screenshots_missing",
    "_shift_page",
    "_strip_canvas_suffix",
    "_strip_colab_dataframe_widgets",
    "_submission_stamp",
    "_table_html_to_markdown",
    "convert_docx_to_markdown",
    "convert_html_to_markdown",
    "convert_ipynb_to_markdown",
    "convert_pdf_to_markdown",
    "convert_pptx_to_markdown",
    "main",
    "pending_preprocess_items",
    "preprocess_assignment",
    "preprocess_item_hashes",
]

if __name__ == "__main__":
    main()
